# Q. 1

In [338]:
from pprint import pprint
import numpy as np

def get_P(mat):
    num_cols = mat.shape[1]
    I = np.identity(num_cols)
    for col in range(num_cols):
        max_row = col + np.argmax(mat[col:,col])
        if max_row != col:
            I[(col,max_row),:] = I[(max_row,col),:]
    return I
 
def get_l_d_u_p(A):
    P = get_P(A)
    A = P.dot(A)
    n = A.shape[0]
    L = np.identity(n)
    U = np.zeros((n,n))
    for i in range(n):
        for j in range(i+1):
            U[j,i] = A[j,i] - U[:j,i].dot(L[j,:j])
        for j in range(i, n):
            L[j,i] = (A[j,i] - U[:i,i].dot(L[j,:i])) / U[i,i]
    D = np.zeros((n,n))
    for i in range(n):
        first = U[i,i]
        D[i,i] = first
        U[i,i:] /= first
    return {'L': L, 'D': D, 'U': U, 'P': P}
 
a = [[1, 3, 5], [2, 4, 7], [1, 1, 0]]
a = np.array(a)

def print_vals(a):
    print("PA=LDU")
    for key,val in get_l_d_u_p(a).items():
        print(key)
        pprint(val)
        print()

def print_svd(u,s,v):
    print("SVD -> A=USV*")
    print('U')
    pprint(u)
    print()
    print('S')
    pprint(s)
    print()
    print('V')
    pprint(v.T)
    print()

# Q. 2

In [339]:
mat = np.array([[4,7,0],[2,2,-6],[3,2,1]])
print_vals(mat)
u,s,v = np.linalg.svd(mat)
print_svd(u,s,v)

PA=LDU
L
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ],
       [ 0.75      ,  2.16666667,  1.        ]])

P
array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

U
array([[ 1.  ,  1.75,  0.  ],
       [ 0.  ,  1.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ]])

D
array([[  4. ,   0. ,   0. ],
       [  0. ,  -1.5,   0. ],
       [  0. ,   0. ,  14. ]])

SVD -> A=USV*
U
array([[ 0.83108771,  0.36392168,  0.42054041],
       [ 0.45440389, -0.88032036, -0.13621004],
       [ 0.3206405 ,  0.30429769, -0.89699085]])

S
array([ 9.33057832,  5.78987054,  1.55489788])

V
array([[ 0.55678008,  0.10500046, -0.82399688],
       [ 0.7896298 ,  0.24100823,  0.56426927],
       [-0.25783856,  0.96482638, -0.05127709]])



In [365]:
mat = np.array([[1,0,0,0,1],
                [0,1,0,1,0],
                [0,0,1,0,0],
                [0,1,0,0,0],
                [1,0,0,0,0]])
print_vals(mat)
u,s,v = np.linalg.svd(mat)
print_svd(u,s,v)

PA=LDU
L
array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 1.,  0.,  0., -0.,  1.]])

P
array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

U
array([[ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -0.],
       [ 0.,  0.,  0.,  0.,  1.]])

D
array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0., -1.]])

SVD -> A=USV*
U
array([[-0.85065081,  0.        ,  0.        , -0.52573111,  0.        ],
       [ 0.        , -0.85065081,  0.        ,  0.        ,  0.52573111],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        , -0.52573111,  0.        ,  0.        ,

In [341]:
mat = np.array([[2,1,3],
               [2,1,2],
               [5,5,5]])
print_vals(mat)
u,s,v = np.linalg.svd(mat)
print_svd(u,s,v)

PA=LDU
L
array([[ 1. ,  0. ,  0. ],
       [ 0.4,  1. ,  0. ],
       [ 0.4,  1. ,  1. ]])

P
array([[ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

U
array([[ 1.,  1.,  1.],
       [ 0.,  1., -1.],
       [ 0.,  0.,  1.]])

D
array([[ 5.,  0.,  0.],
       [ 0., -1.,  0.],
       [ 0.,  0., -1.]])

SVD -> A=USV*
U
array([[-0.36351359,  0.8063118 ,  0.46660385],
       [-0.29987866,  0.37293011, -0.87806373],
       [-0.88200378, -0.45911264,  0.10623054]])

S
array([ 9.79103061,  1.4162264 ,  0.36058604])

V
array([[-0.58592436,  0.04442838, -0.80914693],
       [-0.51816926, -0.78823645,  0.33193962],
       [-0.62305157,  0.61376658,  0.48486836]])



# Q. 3

In [366]:
def solve(A, b):
    u,s,v = np.linalg.svd(A)
    s_inv = np.array([1/x if x>0.000001 else 0 for x in s])
    x = v.T.dot(np.diag(s_inv)).dot(u.T).dot(b.T)
    return x

## a)

In [367]:
A = np.array([[2,1,3],
              [2,1,2],
              [5,5,5]])
b = np.array([[5,-5,0]])

In [368]:
solve(A,b)

array([[-15.],
       [  5.],
       [ 10.]])

## b)

In [445]:
A = np.array([[4,7,0],
              [2,2,-6],
              [1,2,1]])
b = np.array([3,5,1])

In [446]:
u,s,v = np.linalg.svd(A)

In [447]:
s

array([  9.05538514e+00,   5.74456265e+00,   1.05319976e-16])

Third element of s being extremely small compared to the first element of s, indicates a very high condition number. The matrix is singular.

In [451]:
M = np.hstack((A,b.reshape(-1,1)))
pprint(M)

array([[ 4,  7,  0,  3],
       [ 2,  2, -6,  5],
       [ 1,  2,  1,  1]])


In [452]:
u,s,v = np.linalg.svd(M)

In [453]:
s

array([ 10.582197  ,   6.13396284,   0.62578477])

Since the matrix M is not singular, the system contains no solution

In [454]:
solve(A,b)

array([ 0.26644494,  0.31116038, -0.62047302])

Which is the least square solution

## c)

In [455]:
A = np.array([[4,7,0],
              [2,2,-6],
              [1,2,1]])
b = np.array([18,-12,8])

In [456]:
u,s,v = np.linalg.svd(A)

In [457]:
s

array([  9.05538514e+00,   5.74456265e+00,   1.05319976e-16])

Third element of s being extremely small compared to the first element of s, indicates a very high condition number. The matrix is singular.

In [441]:
M = np.hstack((A,b.reshape(-1,1)))

In [442]:
pprint(M)

array([[  4,   7,   0,  18],
       [  2,   2,  -6, -12],
       [  1,   2,   1,   8]])


In [443]:
u,s,v = np.linalg.svd(M)

In [444]:
s

array([  2.40193460e+01,   8.37084320e+00,   2.69857931e-15])

The matrix M is singular, the system of contains infinitely many solutions.

In [414]:
solve(A,b)

array([ 0.78787879,  2.12121212,  2.96969697])